#\u4EE5\u4E0B\u5C31\u662F\u9700\u8981\u5199\u7684\u914D\u7F6E\uFF0C\u6CE8\u610Fbase-package\u5C31\u53EF\u4EE5\u4E86
swagger :
    enable: true	#\u662F\u5426\u5F00\u542Fswagger/\u9ED8\u8BA4false
    api-info:
        description: wim-plus
        license: wim-plus
        license-url: https://github.com/looserMe
        terms-of-service-url: https://github.com/looserMe
        title: IT建设型人才
        version: 2.8.0
        contact:
            email: 1466217938@qq.com
            name: wim
            url: https://github.com/looserMe
    docket:
        base-package: com.wim.web   #\u626B\u63CF\u7684\u8DEF\u5F84/\u57FA\u672C\u5C31\u662F\u4F60\u7684controller\u5305\u4E0B\u9762
        group-name: wim-manage